[package]
name = "bbjwt"
version = "0.1.0"
edition = "2021"
authors = [
  "Markus Thielen <markus.thielen@basebox.tech>",
]

[dependencies]
thiserror = "1.0"
base64 = "0.13"
openssl = "0.10"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
reqwest = { version = "0.11" }
