[package]
name = "bbjwt"
version = "0.1.0"
edition = "2021"
authors = [
  "Markus Thielen <markus.thielen@basebox.tech>",
]

[dependencies]
url = { version = "2.1" }
thiserror = "1.0"
openssl = "0.10"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
reqwest = { version = "0.11" }

[dev-dependencies]
rand = "0.8"
tokio = { version = "1.21.0", features = ["full", "time", "macros"] }
